### ISSUE TITLE
It looks like some #[ctor] was missing

### ISSUE THREAD

**Issue by kookyleo** [mmastrac/rust-ctor#220] opened 2022-06-16 19:13 UTC
I came across something that wasn't easy to understand,
When I referenced a crate that used rust-ctor, It seems that not all of the functions with the #[ctor] flag in Crate are executed, looks like something has been optimized out somewhere, but it seems normal to test crate alone.

I've written an example for simplicity, [https://github.com/kookyleo/a-ctor-failed-case](https://github.com/kookyleo/a-ctor-failed-case)

`git clone https://github.com/kookyleo/a-ctor-failed-case.git`
`cd a-ctor-failed-case`
`cargo run`

And then you can see the weird results.

I got the same results at ubuntu@x86_64 and mac@m1

**Comment by mmastrac** [comment] 2022-06-21 00:33
Interesting. Thanks for the repro. I haven't tested anything, but perhaps it has something to do with all the functions having the same name and contents. The compiler may be aliasing them all to the same function and leaving just a single implementation.

What I'd try as a next step is:

1) Rename the functions and see if it fails again

2) Change the contents of each function to be different (perhaps add a different constant in each one)

I'll see if I can get around to looking at this at some point.

**Comment by mmastrac** [comment] 2022-10-18 21:59
I confirmed that this is because the other file contains no other used functions. Rust is pruning the module entirely, despite it being marked as used. 

By adding a fake function "foo" to the `bar.rs` file and calling that from `lib.rs`, the counter is updated correctly. This is definitely an upstream problem!

**Closed** 2023-05-10 23:09 UTC
